apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  labels:
    name: prometheus-conf
data:
  prometheus.rules: |-
    groups:
    - name: processalert
      rules:
      - alert: Towering Processes
        expr: system_usage{resource_type="Processes"} > 160
        for: 5s
        labels:
          severity: critical
        annotations:
          summary: High Listening Processes
          description: Number of processes are towering on the node
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager"

    scrape_configs:
      - job_name: 'node'
        scrape_interval: 5s
        static_configs:
        - targets: 
          - 10.244.1.77:9998
          - 10.244.2.42:9998
        relabel_configs:
        - source_labels: [__address__]
          regex: '10.244.1.*'
          target_label: instance
          replacement: worker-1
        - source_labels: [__address__]
          regex: '10.244.2.*'
          target_label: instance
          replacement: worker-2
       
