
kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: 'webhook-notifications'
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 5s
 
    receivers:
    - name: 'slack-notifications'
      slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#alertmanager'
        send_resolved: true
    - name: 'webhook-notifications'
      webhook_configs:
      - url: http://my-hunter/test
        send_resolved: true
