kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
      routes:
        - receiver: slack_demo
        # Send severity=slack alerts to slack.
          match:
            severity: slack
          group_wait: 5s
          repeat_interval: 10s
 
    receivers:
    - name: alert-emailer
      email_configs:
      - to: isuru.amarathunga@gmail.com
        send_resolved: true
        from: prometheus.go.exporter@gmail.com
        auth_username: prometheus.go.exporter
        auth_password: xapanapu
        smarthost: smtp.gmail.com:587
        require_tls: false
    - name: slack_demo
      slack_configs:
      - api_url: https://hooks.slack.com/services/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
        channel: '#devops'
        send_resolved: true
